# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix> ];

  boot.loader.systemd-boot.enable = true;
  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = {

    "/boot" = {
      device = "/dev/disk/by-uuid/FB50-CB76";
      fsType = "vfat";
      neededForBoot = true;
    };

    "/" = {
      device = "/dev/disk/by-uuid/7beb17d7-3460-4000-bd29-6883441a9625";
      fsType = "ext4";
      neededForBoot = true;
    };

  };

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
